[package]
name = "ezcd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
log = "0.4.21"

[[bin]]
name = "ezcd-bin"
path = "src/main.rs"


[features]
logging = []
